### PR TITLE
Update docker-compose 1.27.0

### PR DESCRIPTION
**Pull request by gusztavvargadr**
Update docker-compose [1.27.0](https://github.com/docker/compose/releases/tag/1.27.0).

### CODE REVIEW

**Comment by gusztavvargadr** [comment]
@StefanScherer can you please take a look at this at your earliest convenience? 👍

**Review by StefanScherer — APPROVED** [review]
Thank you!
LGTM

**Comment by gusztavvargadr** [comment]
@StefanScherer thanks! Could you please also do a release and a choco push? 👍

**Comment by StefanScherer** [comment]
@gusztavvargadr Yes, will do.
And there also is 1.27.2, but I hadn't the time yesterday. Will update now and do a release.

**Comment by StefanScherer** [comment]
choco package 1.27.2 is in moderation review

**Comment by gusztavvargadr** [comment]
@StefanScherer cheers mate, I missed the releases after 1.27.0 :)

**Pull request merged**
